import type { HTMLAttributes } from "react";

export default function Bomb(props: HTMLAttributes<HTMLButtonElement>) {
  return (
    <button {...props}>
      <svg
        width="50"
        height="50"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 50 50"
      >
        <g id="bomb">
          <rect
            x="5"
            y="5"
            width="40"
            height="40"
            fill="#c0c0c0"
            stroke="#808080"
            stroke-width="1"
          />
          <line
            x1="5"
            y1="5"
            x2="45"
            y2="5"
            stroke="#ffffff"
            stroke-width="1"
          />
          <line
            x1="5"
            y1="5"
            x2="5"
            y2="45"
            stroke="#ffffff"
            stroke-width="1"
          />
          <line
            x1="45"
            y1="5"
            x2="45"
            y2="45"
            stroke="#404040"
            stroke-width="1"
          />
          <line
            x1="5"
            y1="45"
            x2="45"
            y2="45"
            stroke="#404040"
            stroke-width="1"
          />
          <circle cx="25" cy="25" r="8" fill="#000000" />
          <line
            x1="25"
            y1="12"
            x2="25"
            y2="8"
            stroke="#000000"
            stroke-width="2"
          />
          <line
            x1="25"
            y1="38"
            x2="25"
            y2="42"
            stroke="#000000"
            stroke-width="2"
          />
          <line
            x1="12"
            y1="25"
            x2="8"
            y2="25"
            stroke="#000000"
            stroke-width="2"
          />
          <line
            x1="38"
            y1="25"
            x2="42"
            y2="25"
            stroke="#000000"
            stroke-width="2"
          />
          <line
            x1="18"
            y1="18"
            x2="15"
            y2="15"
            stroke="#000000"
            stroke-width="1.5"
          />
          <line
            x1="32"
            y1="32"
            x2="35"
            y2="35"
            stroke="#000000"
            stroke-width="1.5"
          />
          <line
            x1="32"
            y1="18"
            x2="35"
            y2="15"
            stroke="#000000"
            stroke-width="1.5"
          />
          <line
            x1="18"
            y1="32"
            x2="15"
            y2="35"
            stroke="#000000"
            stroke-width="1.5"
          />
          <circle cx="22" cy="22" r="2" fill="#404040" />
        </g>
      </svg>
    </button>
  );
}
