import type { HTMLAttributes } from "react";

export default function Empty(props: HTMLAttributes<HTMLButtonElement>) {
  return (
    <button {...props}>
      <svg
        width="50"
        height="50"
        xmlns="http://www.w3.org/2000/svg"
        viewBox="0 0 50 50"
      >
        <g id="empty">
          <rect
            x="105"
            y="5"
            width="40"
            height="40"
            fill="#c0c0c0"
            stroke="#808080"
            stroke-width="1"
          />
          <line
            x1="105"
            y1="5"
            x2="145"
            y2="5"
            stroke="#ffffff"
            stroke-width="2"
          />
          <line
            x1="105"
            y1="6"
            x2="144"
            y2="6"
            stroke="#dfdfdf"
            stroke-width="1"
          />
          <line
            x1="105"
            y1="5"
            x2="105"
            y2="45"
            stroke="#ffffff"
            stroke-width="2"
          />
          <line
            x1="106"
            y1="5"
            x2="106"
            y2="44"
            stroke="#dfdfdf"
            stroke-width="1"
          />
          <line
            x1="105"
            y1="45"
            x2="145"
            y2="45"
            stroke="#404040"
            stroke-width="2"
          />
          <line
            x1="106"
            y1="44"
            x2="145"
            y2="44"
            stroke="#808080"
            stroke-width="1"
          />
          <line
            x1="145"
            y1="5"
            x2="145"
            y2="45"
            stroke="#404040"
            stroke-width="2"
          />
          <line
            x1="144"
            y1="6"
            x2="144"
            y2="45"
            stroke="#808080"
            stroke-width="1"
          />
        </g>
      </svg>
    </button>
  );
}
